Added testing autoconnection to open networks
AGH-Narzedzia-Informatyczne/God-s-eye pull request #13
Opened 2020-11-16 14:10 UTC by sokoloowski

removed connecting to specified network, now there is scan submitted and connecting to the best network

2020-11-18 12:42 UTC, fiszuuu commented on test/test.ino
> +    if (Serial.available() > 0);
if (Serial.available()>0) //zbędny średnik

2020-11-18 12:45 UTC, fiszuuu commented on test/test.ino
> -    while (WiFi.status() != WL_CONNECTED)
WL_CONNECTED
gdzie jest zadeklarowana ta zmienna? bo w defines jej nie widzę

2020-11-18 12:48 UTC, fiszuuu commented on test/test.ino
> +    Serial.print(netwok);
Serial.print(network)
//literówka

2020-11-18 12:48 UTC, fiszuuu requested changes
lekkie poprawki

2020-11-23 21:35 UTC, sokoloowski commented
All bugs have ben removed, code is fully working now. Testing Wi-Fi scanning and autoconnection, also serial connection is tested. Planning to test monitor mode, HTTP requests and custom action on button press in the nearest future.
![image](https://user-images.githubusercontent.com/39133910/100017958-f7001e80-2ddb-11eb-85d2-159266a74239.png)

2020-11-23 21:37 UTC, sokoloowski commented on test/test.ino
> +    if (Serial.available() > 0);
Poprawione!

2020-11-23 21:38 UTC, sokoloowski commented on test/test.ino
> -    while (WiFi.status() != WL_CONNECTED)
Została już usunięta, dziękuję za uwagę!

2020-11-23 21:38 UTC, sokoloowski commented on test/test.ino
> +    Serial.print(netwok);
Poprawione!

2020-11-24 08:46 UTC, merged