New look with Bootstrap
AGH-Narzedzia-Informatyczne/God-s-eye pull request #18
Opened 2020-11-18 23:30 UTC by echofoxtrotpl

- [ ] Check the live version of website here https://gods-eye-project.herokuapp.com/
- [ ] Look into the *.ejs files in view folder and tell me if something is wrong
- [ ] Check how does the website display on different devices
- [ ] Leave your comments :smile:

2020-11-19 06:49 UTC, echofoxtrotpl commented
![Screenshot_2020-11-19-07-47-43-210_com android chrome](https://user-images.githubusercontent.com/66919607/99631298-a2efe580-2a3b-11eb-8a4d-07e881df7d54.jpg)
One of the problems i don't know how to slove 😞

2020-11-21 19:52 UTC, Tom2rec commented
I think that new look is great :clap: and I don't have any problems with displaying this page - testing on safari mobile and firefox desktop.

2020-11-21 20:00 UTC, sokoloowski commented
> ![Screenshot_2020-11-19-07-47-43-210_com android chrome](https://user-images.githubusercontent.com/66919607/99631298-a2efe580-2a3b-11eb-8a4d-07e881df7d54.jpg)
> One of the problems i don't know how to slove

This pop-up is connected with browser. Google is checking given password with leaked passwords database. I think there was leak from Heroku in the past and one of passwords was like Yours

2020-11-21 20:01 UTC, sokoloowski commented
That look is great! Love it :heart_eyes:

2020-11-21 20:01 UTC, Tom2rec reviewed
I didn't find any suspicious section :+1:

2020-11-21 20:16 UTC, sokoloowski reviewed
Minor changes required in HTML structure

2020-11-21 20:16 UTC, sokoloowski commented on Web/views/index.ejs
> +                  Account
I recommend changing it to "Change password" or creating user info under that link

2020-11-21 20:16 UTC, sokoloowski commented on Web/views/index.ejs
> +                  Server
Unnesessary, as main page is available under link at the very top of sidebar

2020-11-21 20:16 UTC, sokoloowski commented on Web/views/index.ejs
> +                  <span data-feather="server" target="_blank"></span>
`<span>` does not take `target` attribute
```suggestion
                  <span data-feather="server"></span>
```

2020-11-21 20:16 UTC, sokoloowski commented on Web/views/index.ejs
> +            <h1 class="h2">Dashboard</h1>
Just use `<h2>` here!
```suggestion
            <h2>Dashboard</h2>
```

2020-11-21 20:16 UTC, sokoloowski commented on Web/views/login.ejs
> +            <h1 class="h2 mb-3 font-weight-normal">Please sign in</h1>
Just use `<h2>`
```suggestion
            <h2 class="mb-3 font-weight-normal">Please sign in</h2>
```

2020-11-21 20:16 UTC, sokoloowski commented on Web/views/partials/head.ejs
> +    <!-- import tile form acutal request -->
Misspelled "title" in comment
```suggestion
    <!-- import title form acutal request -->
```

2020-11-21 20:16 UTC, sokoloowski commented on Web/views/partials/head.ejs
>      <title>God'sEye | <%= title %></title>
Missing space
```suggestion
    <title>God's Eye | <%= title %></title> 
```

2020-11-21 20:31 UTC, sokoloowski commented
![image](https://user-images.githubusercontent.com/39133910/99886963-d3ed3780-2c40-11eb-909e-f3fcff08ac87.png)
Audit performed via LightHouse in Google Chrome

2020-11-21 20:35 UTC, sokoloowski requested changes
Some changes are really important from SEO point of view:
![image](https://user-images.githubusercontent.com/39133910/99887051-70173e80-2c41-11eb-93c6-4e8089b44d6a.png)
Please, fix your files before merge

2020-11-21 20:35 UTC, sokoloowski commented on Web/views/partials/head.ejs
>      <meta name="viewport" content="width=device-width, initial-scale=1.0">
Document does not have a meta description
```suggestion
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="God sees everything, doesn't He?">
```

2020-11-21 20:55 UTC, echofoxtrotpl commented
Thank you for your advices, I am getting down to work ;)

2020-11-22 20:10 UTC, echofoxtrotpl commented
Everything done, besides SEO optimization. I think that we should do it later because we only need simple website until we have data on it.

2020-11-24 08:53 UTC, sokoloowski approved these changes
Everything seems to be good!

2020-11-24 08:53 UTC, merged